version: "3"

services:
  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/app
      - /app/node_modules # Adicione esta linha para criar um volume anônimo
    tty: true
    ports:
      - "3000:3000"
    # command: sh -c "npm install && node index.js" # Adicionar a node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  node-network:
    driver: bridge
